changes wording and examples slightly
carpentries-incubator/docker-introduction pull request #30
Opened 2020-09-02 19:39 UTC by aturner-epcc

First PR from the updated version of this lesson that @jcohen02 and myself ran online in July 2020. This one does not have many changes, just some minor rewording. The example command used to check if Docker is running correct has been changed from `docker login` to `docker container ls` to avoid describing DockerHub at this point and to link with the initial commands that used in the next episode.

2020-09-02 19:41 UTC, aturner-epcc commented
Realised that the exercises timing was incorrect and fixed

2020-09-03 16:20 UTC, ChristinaLK reviewed
looks fine to me.

2020-09-03 16:20 UTC, ChristinaLK commented on _episodes/02-meet-docker.md
> +> ## You may need to login to Dockerhub
```suggestion
> ## You may need to login to Docker Hub
```

2020-09-03 16:20 UTC, ChristinaLK commented on _episodes/02-meet-docker.md
> +> The Docker application will usually provide a way for you to log in to the Dockerhub using the application's menu (macOS) or systray
```suggestion
> The Docker application will usually provide a way for you to log in to the Docker Hub using the application's menu (macOS) or systray
```

2020-09-03 16:51 UTC, sstevens2 requested changes
I like these changes overall.  I think it is nice to remove the docker login part from this early section and move it to when you need to log in and use docker hub.

I requested a few small changes in my in-line review but would be happy to merge they and @ChristinaLK are addressed.

2020-09-03 16:51 UTC, sstevens2 commented on _episodes/02-meet-docker.md
> +The above command has not actually relied on the part of Docker that runs lightweight virtual machines being operational. Somewhat stretching a physical analogy, you can think of the above Docker com
I find this a bit confusing.  Could we simplify it a bit more?

We should also probably break it up into multiple lines.

2020-09-03 16:51 UTC, sstevens2 commented on _episodes/02-meet-docker.md
> +(The command `docker info` will achieve a similar end. but produces potentially daunting volumes of output.)
```suggestion
(The command `docker info` will achieve a similar end but produces a larger amount of output.)
```

2020-09-08 12:59 UTC, aturner-epcc commented
@sstevens2 Thanks for the comments and suggestions. I have pushed an updated version for you to look at.

2020-09-08 20:54 UTC, sstevens2 commented on _episodes/02-meet-docker.md
> +(The command `docker info` will achieve a similar end. but produces a larger amount of output.)
```suggestion
(The command `docker info` will achieve a similar end but produces a larger amount of output.)
```

2020-09-08 20:56 UTC, merged

2020-09-08 20:56 UTC, sstevens2 commented
Looks good to me.  I'm going to go ahead and merge it.