adds episode discussing how to enable reproducible use of containers
carpentries-incubator/docker-introduction pull request #31
Opened 2020-09-02 20:08 UTC by aturner-epcc

The current version of the lesson has lots of excellent material on using Docker but when we initially ran a workshop using the lesson we thought that there was a gap where we needed to cover how you can use Docker containers to enable reproducibility. This episode is our attempt at producing material to cover that gap.

2020-09-03 16:08 UTC, ChristinaLK commented
This is lovely! thanks @aturner-epcc. 

I really like how this puts the pieces together at the end - as you say in this section, we've really covered the mechanics in this lesson but this circles back to the goals discussed at the beginning, of making our lives easier by using containers. 

No major comments from me. @sstevens2 or @dme26 does one of you want to also review + merge?

2020-09-03 16:08 UTC, ChristinaLK approved these changes

2020-09-03 17:12 UTC, sstevens2 requested changes
I think this episode is a great addition to the lesson.  Please take a look at my suggestions and then I'm happy to merge it in.

2020-09-03 17:12 UTC, sstevens2 commented on _episodes/08-reproducibility.md
> +  - You can access legacy versions of software and underlying dependencies which may not be generally available any more.
Maybe we should add another reason below this line about also keeping a copy of the data with the scripts and analysis in an image?

2020-09-03 17:12 UTC, sstevens2 commented on _episodes/08-reproducibility.md
> +Note that Zenodo is not the only option for archiving and generating persistent DOIs for images. There are other services out there - for example, some organizations may provide their own, equivalent
I love the addition of this section.  Should we write it for them to actually do this process with an image created earlier in the lesson?

2020-09-03 17:12 UTC, sstevens2 commented on _episodes/08-reproducibility.md
> +{: .challenge}
Would be good to have an answer for this challenge, even if it is exhaustive of all the possible answers learners might come up with.

2020-09-03 17:12 UTC, sstevens2 commented on _episodes/08-reproducibility.md
> +cover:
```suggestion
Although you can certainly manage research workflows that use multiple containers manually, there are a number of 
container orchestration tools that you may find useful when managing workflows that use multiple containers. 
We won't go in depth on using these tools in this lesson but instead briefly describe 
a few options and point to useful resources on using these tools to allow you to explore them yourself. :
```

2020-09-23 09:42 UTC, aturner-epcc commented
@sstevens2 Sorry for the delay. Thanks for the great comments - I think I have addressed them all in the latest commit.

2020-09-23 14:54 UTC, sstevens2 commented on _episodes/08-reproducibility.md
> +as closely as possible even if you do not have access to exactly the same hardware resources #
The sentence is written as someone else (except in parentheses) so I think it should be they here. 
```suggestion
as closely as possible even if they do not have access to exactly the same hardware resources #
```

2020-09-23 14:56 UTC, sstevens2 commented
Looks great! Made one small change and will go ahead and merge.

2020-09-23 14:56 UTC, merged